import type { EventDetail } from "@/data/event-detail";

export const detail: EventDetail = {
  slug: "claude-hallucinates-in-court",
  deck: "Anthropic's Claude hallucinated a legal citation inside the company's own $75 million copyright defense, in an expert report arguing the model rarely reproduces copyrighted lyrics.",
  body: [
    "On May 15, 2025, Latham & Watkins associate Ivana Dukanovic filed a declaration in <em>Concord Music Group, Inc. v. Anthropic PBC</em>, a $75 million copyright case before Magistrate Judge Susan van Keulen in the Northern District of California, taking responsibility for an erroneous citation generated by Anthropic's own Claude AI. The citation appeared in an April 30, 2025 expert declaration by Anthropic data scientist Olivia Chen, who had been submitted to support arguments about how rarely Claude reproduces copyrighted song lyrics. Chen's testimony concerned the frequency of protected lyric reproduction; the citation supporting it was produced by the same model being sued for training on those lyrics. The underlying lawsuit was brought in October 2023 by music publishers including Universal Music Group, Concord, and ABKCO, alleging Anthropic used copyrighted lyrics to train Claude without authorization.",
    'Dukanovic explained that she had asked Claude.ai to format a citation for a real source. <a href="https://fortune.com/2025/05/18/anthropic-claude-lawyer-mistake-citation-legal-filing-large-language-model-llm-latham-watkins/">"I asked Claude.ai to provide a properly formatted legal citation for that source using the link to the correct article. Unfortunately, although providing the correct publication title, publication year, and link to the provided source, the returned citation included an inaccurate title and incorrect authors."</a> The genuine article was "Binomial Confidence Intervals for Rare Events: Importance of Defining Margin of Error Relative to Magnitude of Proportion" by Owen McGrath and Kevin Burke, published in <em>The American Statistician</em>. The hallucinated version named authors who, in reality, <a href="https://www.reuters.com/legal/legalindustry/anthropics-lawyers-take-blame-ai-hallucination-music-publishers-lawsuit-2025-05-15/">"have never worked together."</a>',
    'At a hearing, music publishers\' attorney Matt Oppenheim called the citation a <a href="https://decrypt.co/319683/anthropic-accused-of-citing-ai-hallucination-in-song-lyrics-lawsuit">"complete fabrication,"</a> though he added that he did not believe Chen intentionally made it up, suggesting she likely used Claude itself to generate the source. Judge van Keulen called the matter <a href="https://reason.com/volokh/2025/05/26/judge-strikes-part-of-anthropic-claude-ai-experts-declaration-because-of-uncaught-ai-hallucination-in-part-of-citation/">"a very serious and grave issue"</a> and stated that <a href="https://reason.com/volokh/2025/05/26/judge-strikes-part-of-anthropic-claude-ai-experts-declaration-because-of-uncaught-ai-hallucination-in-part-of-citation/">"there\'s a world of difference between a missed citation and a hallucination generated by AI."</a> She ordered Anthropic to respond to the allegations and ultimately struck paragraph 9 of Chen\'s declaration, finding that the issue undermined the overall credibility of her written declaration.',
    'Anthropic\'s filing characterized the error as <a href="https://www.theregister.com/2025/05/15/anthopics_law_firm_blames_claude_hallucinations/">"an honest citation mistake and not a fabrication of authority,"</a> while Dukanovic described it as <a href="https://www.theregister.com/2025/05/15/anthopics_law_firm_blames_claude_hallucinations/">"an embarrassing and unintentional mistake."</a> The company admitted that its "manual citation check" failed to catch the error, along with additional wording errors that Claude introduced during the citation-formatting process. Judge van Keulen noted this was <a href="https://reason.com/volokh/2025/05/26/judge-strikes-part-of-anthropic-claude-ai-experts-declaration-because-of-uncaught-ai-hallucination-in-part-of-citation/">"not a case where attorneys and experts abdicate their independent judgment,"</a> because the underlying article did exist and could be found via a Google search, but she still flagged the failed manual check and the lack of personal verification by trial counsel.',
    "The hallucinated reference was an academic statistics source cited to support Chen's testimony about the frequency with which Claude reproduces protected lyric content. The article's actual title concerned binomial confidence intervals for rare events. In a $75 million case about whether Claude was trained on copyrighted lyrics, the model produced a defective citation while attempting to prove that its own lyric reproduction was statistically uncommon. The citation then became part of the evidence used to challenge the credibility of Anthropic's expert.",
  ],
  receipts: [
    "The hallucinated citation appeared in an April 30, 2025 expert declaration by Anthropic data scientist Olivia Chen.",
    "Latham & Watkins associate Ivana Dukanovic filed a corrective declaration on May 15, 2025.",
    'The genuine article was "Binomial Confidence Intervals for Rare Events: Importance of Defining Margin of Error Relative to Magnitude of Proportion" by Owen McGrath and Kevin Burke, published in The American Statistician.',
    'Music publishers\' attorney Matt Oppenheim called the citation a "complete fabrication."',
    "Judge Susan van Keulen struck paragraph 9 of Chen's declaration, finding the issue undermined the expert's overall credibility.",
    "The underlying lawsuit, brought in October 2023 by publishers including Universal Music Group, is described as a $75 million case.",
  ],
  reactions: [
    {
      platform: "hackernews",
      author: "JumpCrisscross",
      meta: "Hacker News, comment on The Verge submission",
      quote:
        "Default judgement against Anthropic. And sanctions on the Latham attorney who signed this.",
      url: "https://news.ycombinator.com/item?id=44025967",
    },
    {
      platform: "other",
      author: "gurps_npc",
      meta: "Slashdot, Score: 4, Interesting",
      quote:
        "If I lie to a judge, they can charge me with perjury and send me to jail. The fact that they claim the lie was done by a machine they used is not relevant.",
      url: "https://yro.slashdot.org/story/25/05/15/2031207/anthropics-lawyer-forced-to-apologize-after-claude-hallucinated-legal-citation",
    },
    {
      platform: "other",
      author: "Jason Earl",
      meta: "Slashdot, Score: 4, Insightful",
      quote:
        "The problem with that defense is that the article that they cited doesn't actually exist...what they did actually fits the definition of fabrication of authority.",
      url: "https://yro.slashdot.org/story/25/05/15/2031207/anthropics-lawyer-forced-to-apologize-after-claude-hallucinated-legal-citation",
    },
    {
      platform: "other",
      author: "khb",
      meta: "Slashdot, Score: 5, Insightful",
      quote:
        "There have been several such cases in the news over the last two years. I guess the penalties haven't been painful enough to get their attention.",
      url: "https://yro.slashdot.org/story/25/05/15/2031207/anthropics-lawyer-forced-to-apologize-after-claude-hallucinated-legal-citation",
    },
    {
      platform: "hackernews",
      author: "Kon-Peki",
      meta: "Hacker News, comment on The Verge submission",
      quote:
        "Ah, they replaced a boring, well-tested, deterministic piece of automation software with an LLM.",
      url: "https://news.ycombinator.com/item?id=44007968",
    },
  ],
  images: [],
  aftermath:
    "Judge van Keulen struck paragraph 9 of Chen's declaration and cited the hallucination as a blow to the expert's credibility, while noting that trial counsel had failed to personally verify the citation. The ruling now forms part of the record in the ongoing $75 million litigation over whether Anthropic trained Claude on copyrighted song lyrics.",
};
